language: csharp
dist: trusty
sudo: false
solution: FluentMigrator.sln
mono: latest
dotnet: 2.1.103
git:
  depth: false
before_script:
  - nuget install GitVersion.CommandLine -Version 4.0.0-beta0012 -Prerelease
  - export VERSION_SUFFIX=$(mono GitVersion.CommandLine.4.0.0-beta0012/tools/GitVersion.exe /showvariable PreReleaseTag)
script:
  - dotnet restore ./FluentMigrator.sln
  - msbuild ./FluentMigrator.sln /v:m /p:VersionSuffix="$VERSION_SUFFIX"
  - dotnet vstest test/FluentMigrator.Tests/bin/Debug/net47/FluentMigrator.Tests.dll --TestCaseFilter:'TestCategory!=NotWorkingOnMono&(TestCategory!=Integration|(TestCategory=Integration&(TestCategory=SQLite)))'
  - msbuild ./FluentMigrator.sln /v:m /p:VersionSuffix="$VERSION_SUFFIX" /t:Pack /p:PackageOutputPath="$TRAVIS_BUILD_DIR/output"
