language: csharp
dist: trusty
sudo: false
solution: FluentMigrator.sln
mono: latest
dotnet: 2.1.300-preview2-008533
git:
  depth: false
env:
  global:
  - secure: LBwjIieB3lGAb21LFO75eW42F3gm4Af+Wd/y37gbAJC9WXLO6i4aLOIDjaheq9wZEWAjsjLrG9aDf2YgCoiboGLhIVVS2CUEcLL8v9A8fdwG0MMdNbJ+HiwOCro97lZywT32yQ6dDzTf2xcUWufQ2YhQXBE52Ym6hMjkm5iaWnY=
  - secure: SB15HtRpZMuVKKzQ1jGyFqAFb+Dvd1JfB2s7yTp5hd95XSKJ3kS/yTB3edlEpCLi9KZlllBnf7OqoOhUz5QlAjpIRV8VuUUy1YZmMG8V6gTgU0xdWkDUnw83fuDyHlyfQwg+J5UrsDYKq5S+zisqxn4+L792mqAvqJMo25x8rlM=
before_script:
- nuget install GitVersion.CommandLine -Version 4.0.0-beta0012 -Prerelease -ExcludeVersion
- nuget install docfx.console -ExcludeVersion
- export GITVERSION_TOOL="mono GitVersion.CommandLine/tools/GitVersion.exe"
- export DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
- export VERSION_SUFFIX=$($GITVERION_TOOL /showvariable PreReleaseTag)
- echo Using VersionSuffix=$VERSION_SUFFIX
- chmod a+x ./*.sh
script:
- dotnet pack ./FluentMigrator.sln --version-suffix "$VERSION_SUFFIX" -c "Release" -o "$TRAVIS_BUILD_DIR/output" -p:SourceLinkCreate=true
- dotnet test ./test/FluentMigrator.Tests/FluentMigrator.Tests.csproj --filter 'TestCategory!=NotWorkingOnMono&(TestCategory!=Integration|(TestCategory=Integration&(TestCategory=SQLite)))'
- $DOCFX_TOOL metadata docfx_project/docfx.json
- $DOCFX_TOOL build docfx_project/docfx.json
after_success:
- '[[ "$TRAVIS_PULL_REQUEST" == "false" && ("$TRAVIS_BRANCH" == release/* || "$TRAVIS_BRANCH" == develop) ]] && ./myget-upload.sh'
- '[[ "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_TAG =~ ^v[[:digit:]]+(\.[[:digit:]]+)+$ ]] && ./nuget-upload.sh'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: fluentmigrator/fluentmigrator.github.io
  target-branch: master
  local-dir: docfx_project/_site
  keep-history: true
  on:
    branch: feature/docfx
