language: csharp
dist: trusty
sudo: false
solution: FluentMigrator.sln
mono: latest
dotnet: 2.1.103
script:
  - dotnet restore ./FluentMigrator.sln
  - msbuild ./FluentMigrator.sln
  - dotnet vstest test/FluentMigrator.Tests/bin/Debug/net471/FluentMigrator.Tests.dll --TestCaseFilter:'TestCategory!=Integration&TestCategory!=NotWorkingOnMono'
